### ISSUE TITLE
Create .travis.yml

### ISSUE THREAD

**Issue by desevoker** [desevoker/bsa-2019-html-css-test-homepage-dh#24]
```
language: node_js
node_js:
  - 11.13.0
script:
  - npm install --global workbox-cli
  - workbox generateSW workbox-config.js
deploy:
  - provider: s3
    skip_cleanup: true
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    bucket: ________-staging
    region: eu-central-1
    acl: public_read
    on:
      branch: develop
  - provider: s3
    skip_cleanup: true
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    bucket: ________-production
    region: eu-central-1
    acl: public_read
    on:
      branch: master
```
